# Generated by Django 4.2.7 on 2023-12-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cat_slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='photos/categories')),
            ],
        ),
    ]
